<?php

namespace ContainerEdx4Uxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation1TypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Reservation1Type' shared autowired service.
     *
     * @return \App\Form\Reservation1Type
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Reservation1Type'] = new \App\Form\Reservation1Type();
    }
}
