<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdx4Uxv\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdx4Uxv/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEdx4Uxv.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEdx4Uxv\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerEdx4Uxv\App_KernelProdContainer([
    'container.build_hash' => 'Edx4Uxv',
    'container.build_id' => '0748f6da',
    'container.build_time' => 1670686842,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdx4Uxv');
