<?php

namespace ContainerCCZQArW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YvRgUIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yvRgUI_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yvRgUI_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController::new' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.AMGS6oS', 'get_ServiceLocator_AMGS6oSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController:new' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.AMGS6oS', 'get_ServiceLocator_AMGS6oSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\ReservationController::edit' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::new' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\ReservationController:edit' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:new' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
