<?php

namespace ContainerGqQPgW4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RI1EVcZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rI1EVcZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rI1EVcZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CalendarController::delete' => ['privates', '.service_locator.J5ClqNV', 'get_ServiceLocator_J5ClqNVService', true],
            'App\\Controller\\CalendarController::edit' => ['privates', '.service_locator.J5ClqNV', 'get_ServiceLocator_J5ClqNVService', true],
            'App\\Controller\\CalendarController::index' => ['privates', '.service_locator.jPdW3fN', 'get_ServiceLocator_JPdW3fNService', true],
            'App\\Controller\\CalendarController::new' => ['privates', '.service_locator.jPdW3fN', 'get_ServiceLocator_JPdW3fNService', true],
            'App\\Controller\\CalendarController::show' => ['privates', '.service_locator.kh.3Agn', 'get_ServiceLocator_Kh_3AgnService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController::new' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.AMGS6oS', 'get_ServiceLocator_AMGS6oSService', true],
            'App\\Controller\\StudioAfController::index' => ['privates', '.service_locator.PcJCjPz', 'get_ServiceLocator_PcJCjPzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CalendarController:delete' => ['privates', '.service_locator.J5ClqNV', 'get_ServiceLocator_J5ClqNVService', true],
            'App\\Controller\\CalendarController:edit' => ['privates', '.service_locator.J5ClqNV', 'get_ServiceLocator_J5ClqNVService', true],
            'App\\Controller\\CalendarController:index' => ['privates', '.service_locator.jPdW3fN', 'get_ServiceLocator_JPdW3fNService', true],
            'App\\Controller\\CalendarController:new' => ['privates', '.service_locator.jPdW3fN', 'get_ServiceLocator_JPdW3fNService', true],
            'App\\Controller\\CalendarController:show' => ['privates', '.service_locator.kh.3Agn', 'get_ServiceLocator_Kh_3AgnService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.EdH9l1X', 'get_ServiceLocator_EdH9l1XService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController:new' => ['privates', '.service_locator.LyRga8r', 'get_ServiceLocator_LyRga8rService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.AMGS6oS', 'get_ServiceLocator_AMGS6oSService', true],
            'App\\Controller\\StudioAfController:index' => ['privates', '.service_locator.PcJCjPz', 'get_ServiceLocator_PcJCjPzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CalendarController::delete' => '?',
            'App\\Controller\\CalendarController::edit' => '?',
            'App\\Controller\\CalendarController::index' => '?',
            'App\\Controller\\CalendarController::new' => '?',
            'App\\Controller\\CalendarController::show' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\ReservationController::edit' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::new' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Controller\\StudioAfController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CalendarController:delete' => '?',
            'App\\Controller\\CalendarController:edit' => '?',
            'App\\Controller\\CalendarController:index' => '?',
            'App\\Controller\\CalendarController:new' => '?',
            'App\\Controller\\CalendarController:show' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\ReservationController:edit' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:new' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'App\\Controller\\StudioAfController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
