<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEqSOIl9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEqSOIl9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEqSOIl9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEqSOIl9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEqSOIl9\App_KernelDevDebugContainer([
    'container.build_hash' => 'EqSOIl9',
    'container.build_id' => '8911c6a7',
    'container.build_time' => 1670958363,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEqSOIl9');
