<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwK0rYO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwK0rYO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRwK0rYO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRwK0rYO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRwK0rYO\App_KernelDevDebugContainer([
    'container.build_hash' => 'RwK0rYO',
    'container.build_id' => '64a3b6fc',
    'container.build_time' => 1670791574,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwK0rYO');
